name: Portfolio CI
on:
  push:
    paths:
      - "apps/portfolio/**"
  pull_request:
    paths:
      - "apps/portfolio/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/portfolio
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm install
      - run: npm run lint
      - run: npm run build
